declare module 'regression' {
    /** Declaration file generated by dts-gen */

    export function exponential(data: any, supplied: any): any;

    export function linear(data: any, supplied: any): any;

    export function logarithmic(data: any, supplied: any): any;

    export function polynomial(data: any, supplied: any): any;

    export function power(data: any, supplied: any): any;

    export namespace exponential {
        const prototype: {
        };

    }

    export namespace linear {
        const prototype: {
        };

    }

    export namespace logarithmic {
        const prototype: {
        };

    }

    export namespace polynomial {
        const prototype: {
        };

    }

    export namespace power {
        const prototype: {
        };

    }

}